# Welcome to Jekyll!
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Shotlow.com
email: blair.shotlow@gmail.com
description: Our Family.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:
github_username:
facebook_username: 
instagram_username:

social:
  - title:
    url:

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed

include:
  - .nojekyll
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - Gruntfile.coffee
  - node_modules
  - package.json
  - bower_components
  - bower.json
